version: "3.8"

services:
  big-brother-local:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bigbrother
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
